### ISSUE TITLE
Webpage titel is not the website name (but some bs)

### ISSUE THREAD

**Issue by Dwarf-Nebula** [Nouw/smoelenboek#7] opened 2023-09-10 15:31 UTC
![IMG_5686](https://github.com/Nouw/smoelenboek/assets/12648938/23f03ddc-4216-4f67-aa8b-aeb5bd55a83f)

The titel of the website is now “Vite + react + TS”, users don’t need this information and want to know what site is on their unused tabpages.

**Comment by Nouw** [comment] 2023-09-10 17:32
Thank you for reporting. The issue is fixed in cd0aa77e448996188a0d955bc477da209658d1f5, will create a deployment somewhere next week for v4.0.11

**Closed** 2023-09-10 17:32 UTC
